const newsfeed = {
    author: "John Doe",
    profilepic: "https://plus.unsplash.com/premium_photo-1689530775582-83b8abdb5020?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    news: [
      {
        id: 1,
        description: "The world witnessed a monumental shift in the tech industry today, as major players from across the globe gathered to unveil innovations that will define the next decade. From AI-powered robotics to advanced quantum computing, the future is here and it’s beyond imagination.",
        dateandtime: {
          date: "2024-01-01",
          time: "12:00",
        },
        editdate: {
          status: true,
          date: "2024-01-01",
        },
        eventregistered: false,
        comments: [],
        favourites: [], 
      },
      { id: 2,
        description: "In a groundbreaking discovery, scientists have found a way to harness clean energy from a newly discovered material on Mars. The implications of this could completely change how the world approaches energy production and consumption in the coming years.",
        dateandtime: {
          date: "2024-02-15",
          time: "15:30",
        },
        editdate: {
          status: false,
          date: "",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
      },
      { id: 3,
        description: "In a shocking turn of events, the global markets experienced a major crash today, following news of a massive cybersecurity breach affecting major financial institutions. Experts are predicting a turbulent recovery period, with potential ripple effects across several industries.",
        dateandtime: {
          date: "2024-03-22",
          time: "10:15",
        },
        editdate: {
          status: true,
          date: "2024-03-25",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
      },
      { id: 4,
        description: "The newest space mission launched by NASA has achieved an unprecedented milestone by sending back the first high-definition images from a previously unexplored region of Jupiter's moon, Europa. Scientists are eagerly analyzing the data for signs of alien life.",
        dateandtime: {
          date: "2024-04-05",
          time: "09:00",
        },
        editdate: {
          status: false,
          date: "",
        },
        eventregistered: false,
        comments: [],
        favourites: [],
        },
      { id: 5,
        description: "A historic climate agreement has been reached today between the world’s leading nations. The deal includes drastic cuts to carbon emissions and a commitment to achieve net-zero emissions by 2050. Environmental activists are calling this the 'defining moment of the century.'",
        dateandtime: {
          date: "2024-05-10",
          time: "14:45",
        },
        editdate: {
          status: true,
          date: "2024-05-12",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
            },
        { id: 6,
        description: "After years of research and development, a revolutionary cure for Alzheimer's disease has been approved by the FDA. Families and patients across the globe are celebrating this historic medical breakthrough that is expected to change millions of lives.",
        dateandtime: {
          date: "2024-06-18",
          time: "11:00",
        },
        editdate: {
          status: true,
          date: "2024-06-20",
        },
        eventregistered: false,
        comments: [],
        favourites: [],
        },
      { id: 7,
        description: "In an unprecedented sporting event, the world’s top athletes gathered in Tokyo for what is being hailed as the most competitive Olympics in modern history. Several world records were broken in one day, igniting excitement among sports fans worldwide.",
        dateandtime: {
          date: "2024-07-21",
          time: "18:30",
        },
        editdate: {
          status: false,
          date: "",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
      },
      { id: 8,
        description: "A major wildfire has broken out in the Amazon rainforest, threatening to destroy large sections of the world's most critical biodiversity hotspot. International efforts to combat the blaze are underway, but environmentalists warn the damage could be irreversible.",
        dateandtime: {
          date: "2024-08-12",
          time: "13:20",
        },
        editdate: {
          status: false,
          date: "",
        },
        eventregistered: false,
        comments: [],
        favourites: [],
      },
      { id: 9,
        description: "Tech giant InnovateX has just unveiled its newest flagship product, a fully autonomous car that is set to revolutionize the automobile industry. Equipped with cutting-edge AI and zero-emissions technology, the car promises to reshape transportation as we know it.",
        dateandtime: {
          date: "2024-09-29",
          time: "16:10",
        },
        editdate: {
          status: true,
          date: "2024-09-30",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
        },
      { id: 10,
        description: "Global leaders met today for the annual World Economic Forum to discuss the ongoing challenges of global poverty, climate change, and economic instability. The forum concluded with a series of ambitious policy recommendations that aim to reshape the global economy.",
        dateandtime: {
          date: "2024-10-05",
          time: "17:50",
        },
        editdate: {
          status: true,
          date: "2024-10-06",
        },
        eventregistered: false,
        comments: [],
        favourites: [],
      },
      { id: 11,
        description: "In an emotional ceremony, Nobel Peace Prize laureates were announced today, honoring activists who have fought tirelessly for human rights and global peace. The winners’ stories of courage and resilience are being celebrated around the world.",
        dateandtime: {
          date: "2024-11-11",
          time: "08:45",
        },
        editdate: {
          status: false,
          date: "",
        },
        eventregistered: true,
        comments: [],
        favourites: [],
      },
    ],
  };
  

export default newsfeed;
  